### ISSUE TITLE
zpl file

### ISSUE THREAD

**Issue by MinaMohsen** [dimagi/zebra-print-android#2]
Hi , please help me , iam new to print with zebra and i need to know what is zpl file and how to generate it ??
Thanks in advanve

**Comment by ctsims** [comment]
ZPL is Zebra's portable label template format and can be created in a number of ways [including tools provided by the company](https://www.zebra.com/us/en/products/software/barcode-printers/zebralink/zebra-designer.html).

Generating ZPL labels is outside of the scope of this library (which is just for printing them once generated), so I'm going to close out this issue. A resource like StackOverflow will likely be more helpful if you have additional questions.
